### ISSUE TITLE
Logs are showing validation errors: Invalid enum member athlete

### ISSUE THREAD

**Issue by obscurerichard** [freezingsaddles/freezing-nq#3]
Doing `docker logs freezing-nq` is yielding errors of this form:

```
[2019-01-13 15:38:17 +0000] [9] [ERROR] Error handling request /webhook
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/dist-packages/falcon/api.py", line 242, in __call__
    responder(req, resp, **params)
  File "/usr/local/lib/python3.6/dist-packages/freezing/nq/api/webhook.py", line 53, in on_post
    result: SubscriptionUpdate = schema.load(req.media).data
  File "/usr/local/lib/python3.6/dist-packages/marshmallow/schema.py", line 580, in load
    result, errors = self._do_load(data, many, partial=partial, postprocess=True)
  File "/usr/local/lib/python3.6/dist-packages/marshmallow/schema.py", line 701, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'object_type': ['Invalid enum member athlete']}
```

**Comment by obscurerichard** [comment]
We must have fixed this a long time ago. There's nothing in the logs for the past year matching this error.

```
fields @timestamp, @message, @logStream, @log
| sort @timestamp desc
| filter @message like /marshmallow.exceptions.ValidationError/
| limit 10000
``` 

This query yielded no matches.
